name: Trivi Scan
on:
    workflow_call: 
        inputs:
            docker_image:
                required: true
                type: string
                description: "Tag da imagem que deve ser escaneada"
jobs:
    scan:
        runs-on: ubuntu-latest
        steps:
          - name: Executar o scan de vulnerabilidade
            uses: aquasecurity/trivy-action@0.20.0
            with:
              image-ref: ${{ inputs.docker_image }}
              scan-type: image
              format: 'json'
              exit-code: 0
              output: 'resultado-trivy.json'
              severity: UNKNOWN,CRITICAL,HIGH,MEDIUM,LOW
          
          - name: Upload do arquivo de resultado do trivy
            uses: actions/upload-artifact@v4
            with:
              name: trivy
              path: resultado-trivy.json
